# Generated by Django 5.2 on 2026-02-04 16:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Владелец', 'verbose_name_plural': 'Владельцы'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите номер в формате +79998887766', regex='^\\+?\\d{10,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('female', 'Женский'), ('male', 'Мужской')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='main.owner'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('bird', 'Птица'), ('bunny', 'Кролик')], max_length=20),
        ),
    ]
